### ISSUE TITLE
Installing vo_estimate and pronto

### ISSUE THREAD

**Issue by mcamurri** [robotperception/vo_estimate#2]
I'm trying to run the VO together with pronto. 

If I've understood correctly, pronto accepts `update_t` messages generated by this module (`vo_estimate`), which is getting the Multisense SL images as source.

Here's the step I've followed:
- I've updated `pronto` to accept Fovis as source
- I've installed `libfovis`, following the instructions in the original repository
- I've starting building the project, but there are unmet dependencies: (`image_io_utils`, `estimate-pose`, ...)

What is the correct procedure to resolve these dependencies? 

Thanks.

**Comment by mauricefallon** [comment]
`If I've understood correctly, pronto accepts update_t messages generated by this module (vo_estimate), which is getting the Multisense SL images as source.`

... Yes, very simple: image in, update to pronto out

vo_estimate is built as part of our navigation stack:
https://github.com/robotperception/rpg-navigation

All the missing dependencies are mentioned there including
https://github.com/openhumanoids/cv_utils
https://github.com/openhumanoids/estimate-pose

So just add them, libfovis and vo_estimate as submodules to your pronto-distro.

Please be patient so we can test it here. Focus on the lidar odometry for now

**Comment by mcamurri** [comment]
Ok, no problem. 
Since I was mentioned quite a few today, you just sparkled my curiosity :)

**Comment by mauricefallon** [comment]
I have dls-fusion running on my computer. for the first time ;)

to work on the VO: should I rebase your pronto branch (remove-history) on the tip of master?

**Comment by mcamurri** [comment]
Yes.
I've done it already locally, but I haven't force-pushed it.
If you have problems, let me know and I will force-push and update the submodules.
